<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.0.3" />
    <PackageReference Include="MassTransit" Version="8.0.0" />
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.0.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\EventBus\BulletinBoard.EventBus.Messages\BulletinBoard.EventBus.Messages.csproj" />
    <ProjectReference Include="..\BulletinBoard.NotificationService.Domain\BulletinBoard.NotificationService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Notification\Queries\" />
    <Folder Include="User\Queries\" />
  </ItemGroup>

</Project>
